const {stylesheetPaths,copyStyles}=require('./site_styles.cjs');
const fs=require('node:fs'),path=require('node:path'),{head,metadata,esc}=require('./site_metadata.cjs');const {renderHeader,renderFooter}=require('./site_chrome.mjs');const root=__dirname,arg=process.argv.indexOf('--output');if(arg<0||!process.argv[arg+1])throw Error('Pass the worker static-site directory with --output');const out=path.resolve(process.argv[arg+1]);if(!fs.existsSync(path.join(out,'sitemap-pages.xml')))throw Error('Expected an existing Polynite Explore site');
const pages={'':'explore','create':'create','about':'about','mcp':'explore-mcp','glb-viewer':'glb-viewer','glb-optimizer':'glb-optimizer','reduce-polygons':'reduce-polygons'};
for(const [route,key]of Object.entries(pages)){const url='https://explore.polynite.io/'+(route?route+'/':''),body=fs.readFileSync(path.join(root,'public-site-src/explore-'+(route||'home')+'.html'),'utf8');const nav=[['/','Explore'],['/create/','Create'],['/discover/','Discover'],['/mcp/','AI & MCP'],['https://polynite.io/docs/','Docs']];const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${head(key,url,{breadcrumbs:route?[['Polynite Explore','https://explore.polynite.io/'],[metadata.pages[key].title,url]]:[['Polynite Explore',url]]})}<link rel="stylesheet" href="${stylesheetPaths.body}"><link rel="stylesheet" href="${stylesheetPaths.chrome}"></head><body><a class="skip" href="#content">Skip to content</a>${renderHeader({section:"Explore",current:route===""?"Explore":route==="create"?"Create":route==="mcp"?"AI & MCP":""})}<main id="content">${body}</main>${renderFooter()}</body></html>`;const dir=path.join(out,route);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html);}
fs.mkdirSync(path.join(out,'assets/public-site'),{recursive:true});fs.copyFileSync(path.join(root,'public-site-src/style.css'),path.join(out,'assets/public-site/style.css'));fs.copyFileSync(path.join(root,'public-site-src/chrome.css'),path.join(out,'assets/public-site/chrome.css'));fs.copyFileSync(path.join(root,'site_chrome.mjs'),path.join(out,'../src/site_chrome.js'));fs.copyFileSync(path.join(root,'assets/og-create-view-share-v2.png'),path.join(out,'assets/og-create-view-share-v2.png'));fs.copyFileSync(path.join(root,'assets/og-create-view-share-v2.png'),path.join(out,'assets/og-cover.png'));
fs.writeFileSync(path.join(out,'sitemap-pages.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${Object.keys(pages).concat('discover').map(route=>`<url><loc>https://explore.polynite.io/${route?route+'/':''}</loc></url>`).join('')}</urlset>`);
console.log('Built seven Explore pages, shared assets and canonical sitemap.');

copyStyles(out);fs.writeFileSync(path.join(out,'../src/site_assets.js'),'export const CHROME_STYLESHEET='+JSON.stringify(stylesheetPaths.chrome)+';');
