const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=__dirname,{esc}=require('./site_metadata.cjs');
const reports=JSON.parse(fs.readFileSync(path.join(root,'public-site-src/tutorial-rendered.json'),'utf8'));
const content=[
 ['colourful-tower','A colourful tower','Beginner','creation','Start with 28 blocks, then make it your own.','Create a tower with seven layers of four cubes. Use cyan, pink and yellow. Frame the whole tower and slowly orbit around it.'],
 ['block-explosion','A burst of colour','Advanced','physics','Launch, freeze the action, orbit and let it tumble.','Create a colourful block explosion with a dramatic cinematic style.'],
 ['orbiting-letters','Words in orbit','Intermediate','text','A real 3D ring of letters around a simple shape.','Create a cyan sphere and a golden 3D ring reading CREATE / VIEW / SHARE around it. Anchor the ring in world space, rotate it slowly and orbit the camera.']
];
const origin='https://polynite.io',media='/docs/media/tutorials/r1/';
const items=content.map(([id,title,level,topic,description,prompt])=>{const r=reports.find(r=>r.id===id);if(!r)throw Error('Missing rendered example '+id);const media=r.media||'/docs/media/tutorials/r1/';if(!/^\/docs\/media\/tutorials\/r[1-9][0-9]*\/$/.test(media)||!new RegExp('^'+id+'-[a-f0-9]{12}\\.scene$').test(r.scene)||r.video!==id+'.mp4')throw Error('Invalid tutorial asset address');return {id,revision:r.revision||1,title,level,topic,description,prompt,scene:origin+media+r.scene,video:origin+media+r.video,preview:origin+media+id+'-preview.mp4',poster:origin+media+id+'.jpg',open:origin+'/tutorials/'+id+'/',sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,media,r.scene))).digest('hex')};});
const script=fs.readFileSync(path.join(root,'public-site-src/tutorials.js'));const scriptName='tutorials-'+crypto.createHash('sha256').update(script).digest('hex').slice(0,12)+'.js';
const cards=items.map(i=>`<article class="tutorial-card" data-tags="${i.level.toLowerCase()} ${i.topic}" data-full-video="${i.video}"><div class="tutorial-media"><video muted playsinline loop preload="none" poster="${i.poster}" aria-label="Preview: ${esc(i.title)}"><source src="${i.preview}" type="video/mp4"></video><button class="watch" data-watch aria-label="Watch ${esc(i.title)} in a large player">▶ Watch</button></div><div class="tutorial-body"><span class="level">${i.level}</span><h3>${esc(i.title)}</h3><p>${esc(i.description)}</p><a class="button primary" data-scene href="${i.open}">Open scene ↗</a><details><summary>Try the prompt</summary><p class="prompt" id="prompt-${i.id}">${esc(i.prompt)}</p><button class="button prompt-copy" data-copy="prompt-${i.id}">Copy prompt</button><p class="tutorial-hint">Connect your assistant to recreate it, then change the colours, scale or camera.</p></details></div></article>`).join('');
const gallery=`<section id="examples"><div class="section-heading"><div><p class="eyebrow">Watch · Explore · Make it yours</p><h2>Tutorials you can play with</h2></div><span id="tutorial-count" role="status">${items.length} tutorials</span></div><div class="tutorial-filters" role="group" aria-label="Filter tutorials">${[['all','All'],['beginner','Beginner'],['intermediate','Intermediate'],['advanced','Advanced'],['creation','Creation'],['physics','Physics'],['text','Text']].map(([value,label])=>`<button data-filter="${value}" aria-pressed="${value==='all'}">${label}</button>`).join('')}</div><div class="tutorial-grid">${cards}</div><p class="muted">Hover for a silent preview on desktop. Watch with sound in the large player, or open a scene directly. No AI connection is needed to explore.</p></section><dialog id="tutorial-player" aria-labelledby="player-title"><div class="player-heading"><h2 id="player-title">Tutorial</h2><button class="button" data-close aria-label="Close video">✕</button></div><video controls playsinline preload="none"></video><div class="actions"><a class="button primary" data-scene>Open scene ↗</a><span class="muted">Enable sound to hear Polynite’s signature.</span></div></dialog><script src="${origin}/assets/public-site/${scriptName}" defer></script>`;
fs.writeFileSync(path.join(root,'public-site-src/tutorials-gallery.html'),gallery);
for(const base of [root,path.join(root,'web'),path.join(root,'dev')]){
 fs.mkdirSync(path.join(base,'assets/public-site'),{recursive:true});fs.writeFileSync(path.join(base,'assets/public-site',scriptName),script);
 fs.mkdirSync(path.join(base,media),{recursive:true});for(const i of items)for(const url of [i.scene,i.video,i.preview,i.poster]){const rel=new URL(url).pathname;const source=path.join(root,rel);fs.mkdirSync(path.dirname(path.join(base,rel)),{recursive:true});if(base!==root)fs.copyFileSync(source,path.join(base,rel));}
 const viewerDir=path.join(base,'tutorial-view');fs.mkdirSync(viewerDir,{recursive:true});
 const runtime=fs.readFileSync(path.join(base,'app.html'),'utf8');
 const isolate=`function(){const persistentMount=FS.mount;FS.mount=function(type,options,mountpoint){return persistentMount.call(FS,type===IDBFS?MEMFS:type,options,mountpoint);};console.info('[tutorial] scene filesystem is temporary; saved scenes are untouched');}`;
 if(!runtime.includes('preRun: [],'))throw Error('Engine bootstrap changed: review tutorial filesystem isolation');
 const ephemeral='<base href="/"><script>window.vmeshAutoDiscover=false;</script>';
 fs.writeFileSync(path.join(viewerDir,'index.html'),runtime.replace('<head>','<head>'+ephemeral).replace('preRun: [],','preRun: ['+isolate+'],').replace('src="welcome.js"','src="welcome.js?v='+crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'welcome.js'))).digest('hex').slice(0,12)+'"'));
 const dir=path.join(base,'tutorials');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'catalog.json'),JSON.stringify({version:1,items},null,2));
 for(const i of items){const entry=path.join(dir,i.id);fs.mkdirSync(entry,{recursive:true});fs.writeFileSync(path.join(entry,'index.html'),require('./tutorial_view_page.cjs')(i));}
}
console.log('Built shared tutorial catalogue, three playable scene entries and gallery.');
