const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=__dirname,{esc}=require('./site_metadata.cjs');
const reports=JSON.parse(fs.readFileSync(path.join(root,'public-site-src/tutorial-rendered.json'),'utf8'));
const content=JSON.parse(fs.readFileSync(path.join(root,'public-site-src/tutorial-content.json'),'utf8'));
const origin='https://polynite.io',media='/docs/media/tutorials/r1/';
const items=content.map(({id,title,level,topic,description,prompt,steps,preset,control,control_note,portrait})=>{const r=reports.find(r=>r.id===id);if(!r)throw Error('Missing rendered example '+id);const media=r.media||'/docs/media/tutorials/r1/';if(!/^\/docs\/media\/tutorials\/r[1-9][0-9]*\/$/.test(media)||!new RegExp('^'+id+'-[a-f0-9]{12}\\.scene$').test(r.scene)||r.video!==id+'.mp4')throw Error('Invalid tutorial asset address');return {id,...(portrait?{portrait:true}:{}),...(steps?{steps}:{}),...(preset?{preset}:{}),...(control?{control}:{}),...(control_note?{control_note}:{}),revision:r.revision||1,title,level,topic,description,prompt,scene:origin+media+r.scene,video:origin+media+r.video,preview:origin+media+id+'-preview.mp4',poster:origin+media+id+'.jpg',open:origin+'/tutorials/'+id+'/',sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,media,r.scene))).digest('hex')};});
const script=fs.readFileSync(path.join(root,'public-site-src/tutorials.js'));const scriptName='tutorials-'+crypto.createHash('sha256').update(script).digest('hex').slice(0,12)+'.js';
const cards=items.map(i=>`<article class="tutorial-card" data-tags="${i.level.toLowerCase()} ${i.topic}" data-full-video="${i.video}"><div class="tutorial-media${(i.portrait||i.id==='ending-signature')?' portrait-media':''}"><video muted playsinline loop preload="none" poster="${i.poster}" aria-label="Preview: ${esc(i.title)}"><source src="${i.preview}" type="video/mp4"></video><button class="watch" data-watch aria-label="Watch ${esc(i.title)} in a large player">▶ Watch</button></div><div class="tutorial-body"><span class="level">${i.level}</span><h3>${esc(i.title)}</h3>${i.preset?`<p><code>${esc(i.preset)}</code></p>`:''}<p>${esc(i.description)}</p><a class="button primary" data-scene href="${i.open}">Open scene ↗</a><details><summary>Try it step by step</summary><p class="prompt" id="prompt-${i.id}">${esc(i.prompt)}</p><button class="button prompt-copy" data-copy="prompt-${i.id}">Copy prompt</button><p class="tutorial-hint">Connect your assistant to recreate it, then make it your own.</p>${i.steps?`<ol class="tutorial-steps">${i.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol>`:''}${i.control?`<details class="tutorial-control"><summary>MCP example</summary>${i.control_note?`<p class="tutorial-hint">${esc(i.control_note)}</p>`:''}${i.control.operation?'<p class="tutorial-hint">Use <code>polynite_scene</code> with these arguments and a fresh <code>action_id</code>. Keep the current scene.</p>':'<p class="tutorial-hint">Use <code>polynite_scene</code> with <code>operation: local</code>, <code>method: scene.cinematic</code>, a new <code>action_id</code>, and this object as <code>params.request</code>. <code>replace</code> changes the whole timeline; keep existing steps when editing.</p>'}<pre><code>${esc(JSON.stringify(i.control,null,2))}</code></pre></details>`:''}</details></div></article>`).join('');
const gallery=`<section id="examples"><div class="section-heading"><div><p class="eyebrow">Watch · Explore · Make it yours</p><h2>Tutorials you can play with</h2></div><span id="tutorial-count" role="status">${items.length} tutorials</span></div><div class="tutorial-filters" role="group" aria-label="Filter tutorials">${[['all','All'],['beginner','Beginner'],['intermediate','Intermediate'],['advanced','Advanced'],['creation','Creation'],['physics','Physics'],['text','Text'],['camera','Camera'],['cinematic','Cinematic'],['export','Export']].map(([value,label])=>`<button data-filter="${value}" aria-pressed="${value==='all'}">${label}</button>`).join('')}</div><div class="tutorial-grid">${cards}</div><p class="muted">Hover for a silent preview on desktop. Watch with sound in the large player, or open a scene directly. No AI connection is needed to explore.</p></section><dialog id="tutorial-player" aria-labelledby="player-title"><div class="player-heading"><h2 id="player-title">Tutorial</h2><button class="button" data-close aria-label="Close video">✕</button></div><video controls playsinline preload="none"></video><div class="actions"><a class="button primary" data-scene>Open scene ↗</a><span class="muted">Enable sound to hear Polynite’s signature.</span></div></dialog><script src="${origin}/assets/public-site/${scriptName}" defer></script>`;
fs.writeFileSync(path.join(root,'public-site-src/tutorials-gallery.html'),gallery);
for(const base of [root,path.join(root,'web'),path.join(root,'dev')]){
 fs.mkdirSync(path.join(base,'assets/public-site'),{recursive:true});fs.writeFileSync(path.join(base,'assets/public-site',scriptName),script);
 fs.mkdirSync(path.join(base,media),{recursive:true});for(const i of items)for(const url of [i.scene,i.video,i.preview,i.poster]){const rel=new URL(url).pathname;const source=path.join(root,rel);fs.mkdirSync(path.dirname(path.join(base,rel)),{recursive:true});if(base!==root)fs.copyFileSync(source,path.join(base,rel));}
 const viewerDir=path.join(base,'tutorial-view');fs.mkdirSync(viewerDir,{recursive:true});
 const runtime=fs.readFileSync(path.join(base,'app.html'),'utf8').replace(/<script id="pn-build-version">[^]*?<\/script>/g,'');
 const isolate=`function(){const persistentMount=FS.mount;FS.mount=function(type,options,mountpoint){return persistentMount.call(FS,type===IDBFS?MEMFS:type,options,mountpoint);};console.info('[tutorial] scene filesystem is temporary; saved scenes are untouched');}`;
 if(!runtime.includes('preRun: [],'))throw Error('Engine bootstrap changed: review tutorial filesystem isolation');
 const release=fs.readFileSync(path.join(root,'version.txt'),'utf8').trim();
 const ephemeral='<script id="pn-build-version">window.__pnBuildVersion='+JSON.stringify(release)+';</script><base href="/"><script>window.vmeshAutoDiscover=false;window.__pnEmbedVersion="tutorial";</script>';
 fs.writeFileSync(path.join(viewerDir,'index.html'),runtime.replace('<head>','<head>'+ephemeral).replace('preRun: [],','preRun: ['+isolate+'],').replace('src="welcome.js"','src="welcome.js?v='+crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'welcome.js'))).digest('hex').slice(0,12)+'"'));
 const dir=path.join(base,'tutorials');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'catalog.json'),JSON.stringify({version:1,items},null,2));
 for(const i of items){const entry=path.join(dir,i.id);fs.mkdirSync(entry,{recursive:true});fs.writeFileSync(path.join(entry,'index.html'),require('./tutorial_view_page.cjs')(i));}
}
console.log('Built shared tutorial catalogue, '+items.length+' playable scene entries and gallery.');
