const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=__dirname,{esc}=require('./site_metadata.cjs');
const reports=JSON.parse(fs.readFileSync(path.join(root,'public-site-src/tutorial-rendered.json'),'utf8'));
const content=[
 ['colourful-tower','A colourful tower','Beginner','creation','Start with 28 blocks, then make it your own.','Create a tower with seven layers of four cubes. Use cyan, pink and yellow. Frame the whole tower and slowly orbit around it.'],
 ['block-explosion','A burst of colour','Advanced','physics','Pause, launch and watch the blocks tumble.','Create a compact 4 × 4 × 4 cluster of colourful physical blocks. Hold for 1.3 seconds, then launch the blocks outward and upward. Add a large Explosion title that fades before the blast. Record a six-second MP4.'],
 ['orbiting-letters','Words in orbit','Intermediate','text','A real 3D ring of letters around a simple shape.','Create a cyan sphere and a golden 3D ring reading CREATE / VIEW / SHARE around it. Anchor the ring in world space, rotate it slowly and orbit the camera.']
];
const origin='https://polynite.io',media='/docs/media/tutorials/r1/';
const items=content.map(([id,title,level,topic,description,prompt])=>{const r=reports.find(r=>r.id===id);if(!r)throw Error('Missing rendered example '+id);const media=r.media||'/docs/media/tutorials/r1/';if(!/^\/docs\/media\/tutorials\/r[1-9][0-9]*\/$/.test(media)||!new RegExp('^'+id+'-[a-f0-9]{12}\\.scene$').test(r.scene)||r.video!==id+'.mp4')throw Error('Invalid tutorial asset address');return {id,revision:r.revision||1,title,level,topic,description,prompt,scene:origin+media+r.scene,video:origin+media+r.video,preview:origin+media+id+'-preview.mp4',poster:origin+media+id+'.jpg',open:origin+'/tutorials/'+id+'/',sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,media,r.scene))).digest('hex')};});
const script=fs.readFileSync(path.join(root,'public-site-src/tutorials.js'));const scriptName='tutorials-'+crypto.createHash('sha256').update(script).digest('hex').slice(0,12)+'.js';
const cards=items.map(i=>`<article class="tutorial-card" data-tags="${i.level.toLowerCase()} ${i.topic}" data-full-video="${i.video}"><div class="tutorial-media"><video muted playsinline loop preload="none" poster="${i.poster}" aria-label="Preview: ${esc(i.title)}"><source src="${i.preview}" type="video/mp4"></video><button class="watch" data-watch aria-label="Watch ${esc(i.title)} in a large player">▶ Watch</button></div><div class="tutorial-body"><span class="level">${i.level}</span><h3>${esc(i.title)}</h3><p>${esc(i.description)}</p><a class="button primary" data-scene href="${i.open}">Open scene ↗</a><details><summary>Try the prompt</summary><p class="prompt" id="prompt-${i.id}">${esc(i.prompt)}</p><button class="button prompt-copy" data-copy="prompt-${i.id}">Copy prompt</button><p class="tutorial-hint">Connect your assistant to recreate it, then change the colours, scale or camera.</p></details></div></article>`).join('');
const gallery=`<section id="examples"><div class="section-heading"><div><p class="eyebrow">Watch · Explore · Make it yours</p><h2>Tutorials you can play with</h2></div><span id="tutorial-count" role="status">${items.length} tutorials</span></div><div class="tutorial-filters" role="group" aria-label="Filter tutorials">${[['all','All'],['beginner','Beginner'],['intermediate','Intermediate'],['advanced','Advanced'],['creation','Creation'],['physics','Physics'],['text','Text']].map(([value,label])=>`<button data-filter="${value}" aria-pressed="${value==='all'}">${label}</button>`).join('')}</div><div class="tutorial-grid">${cards}</div><p class="muted">Hover for a silent preview on desktop. Watch with sound in the large player, or open a scene directly. No AI connection is needed to explore.</p></section><dialog id="tutorial-player" aria-labelledby="player-title"><div class="player-heading"><h2 id="player-title">Tutorial</h2><button class="button" data-close aria-label="Close video">✕</button></div><video controls playsinline preload="none"></video><div class="actions"><a class="button primary" data-scene>Open scene ↗</a><span class="muted">Enable sound to hear Polynite’s signature.</span></div></dialog><script src="${origin}/assets/public-site/${scriptName}" defer></script>`;
fs.writeFileSync(path.join(root,'public-site-src/tutorials-gallery.html'),gallery);
for(const base of [root,path.join(root,'web'),path.join(root,'dev')]){
 fs.mkdirSync(path.join(base,'assets/public-site'),{recursive:true});fs.writeFileSync(path.join(base,'assets/public-site',scriptName),script);
 fs.mkdirSync(path.join(base,media),{recursive:true});for(const i of items)for(const url of [i.scene,i.video,i.preview,i.poster]){const rel=new URL(url).pathname;const source=path.join(root,rel);fs.mkdirSync(path.dirname(path.join(base,rel)),{recursive:true});if(base!==root)fs.copyFileSync(source,path.join(base,rel));}
 const viewerDir=path.join(base,'tutorial-view');fs.mkdirSync(viewerDir,{recursive:true});
 const runtime=fs.readFileSync(path.join(base,'app.html'),'utf8');
 const isolate=`function(){const persistentMount=FS.mount;FS.mount=function(type,options,mountpoint){return persistentMount.call(FS,type===IDBFS?MEMFS:type,options,mountpoint);};console.info('[tutorial] scene filesystem is temporary; saved scenes are untouched');}`;
 if(!runtime.includes('preRun: [],'))throw Error('Engine bootstrap changed: review tutorial filesystem isolation');
 const ephemeral='<base href="/"><script>window.vmeshAutoDiscover=false;</script>';
 fs.writeFileSync(path.join(viewerDir,'index.html'),runtime.replace('<head>','<head>'+ephemeral).replace('preRun: [],','preRun: ['+isolate+'],'));
 const dir=path.join(base,'tutorials');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'catalog.json'),JSON.stringify({version:1,items},null,2));
 for(const i of items){const entry=path.join(dir,i.id);fs.mkdirSync(entry,{recursive:true});fs.writeFileSync(path.join(entry,'index.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(i.title)} — Polynite Tutorial</title><meta name="description" content="${esc(i.description)} Open the interactive scene and create your own variation."><meta property="og:title" content="${esc(i.title)} — Polynite"><meta property="og:description" content="${esc(i.description)}"><meta property="og:image" content="${i.poster}"><meta property="og:url" content="${i.open}"><link rel="canonical" href="${i.open}"><style>html,body{height:100%;margin:0;background:#0b0d12;color:#e8eef7;font:15px system-ui}body{display:flex;flex-direction:column;height:100dvh}header{flex-shrink:0;display:flex;gap:16px;align-items:center;padding:12px;flex-wrap:wrap}a{color:#4fd1e0}button:disabled{opacity:.45;cursor:wait}button{padding:8px 14px;background:#4fd1e0;border:0;border-radius:6px;cursor:pointer}iframe{width:100%;flex:1;min-height:0;border:0}#status{font-size:13px;padding:8px;margin:0}</style></head><body><header><a href="https://explore.polynite.io/docs/">← Tutorials</a><strong>${esc(i.title)}</strong><button id="replay" disabled>Play / replay</button><button id="stop" disabled>Stop</button><button id="save" disabled>Save my version</button><a href="${i.scene}" download>Reference scene</a><a id="download" hidden>Download my version</a></header><p id="status" role="status">Loading your own tutorial viewer…</p><iframe src="/tutorial-view/?tutorial_view=1" title="Polynite interactive tutorial"></iframe><script>
const frame=document.querySelector('iframe'),status=document.querySelector('#status'),replay=document.querySelector('#replay'),save=document.querySelector('#save'),stop=document.querySelector('#stop'),download=document.querySelector('#download');let engine,reference,downloadUrl;
const until=Date.now()+90000;const timer=setInterval(async()=>{try{engine=frame.contentWindow.polynite;if(!engine?.call){if(Date.now()>until){clearInterval(timer);status.textContent='Viewer did not become ready. Check WebGPU support or download the scene copy.';}return;}if(engine.call('scene.cinematic',{request:{command:'status'}}).export.active)throw Error('Viewer is busy');clearInterval(timer);const response=await fetch(${JSON.stringify(new URL(i.scene).pathname)});if(!response.ok)throw Error('Scene download failed');const document=await response.json();reference=structuredClone(document);if(!engine.call('scene.describe').sound?.live&&!engine.call('scene.capabilities').cinematic?.branding)document.seq=document.seq.filter(clip=>clip.op!=='sound');engine.call('scene.cinematic',{request:{command:'load_document',document,start_paused:true}});engine.call('scene.cinematic',{request:{command:'seek',time:0}});replay.disabled=false;save.disabled=false;stop.disabled=false;status.textContent='Explore and edit this temporary copy. Save your version before closing.';}catch(error){clearInterval(timer);status.textContent='Could not open the tutorial: '+error.message+' — download the scene copy to try locally.';}if(Date.now()>until){clearInterval(timer);status.textContent='Viewer did not become ready. Check WebGPU support or download the scene copy.';}},250);
replay.addEventListener('click',()=>{try{engine.call('scene.cinematic',{request:{command:'stop'}});if(!engine.call('scene.describe').sound?.live)status.textContent='Playing silently. Use the viewer audio control for sound; the video player includes the signature.';if(engine.call('scene.physics',{request:{command:'status'}}).body_count){engine.call('scene.physics',{request:{command:'resume'}});engine.call('scene.cinematic',{request:{command:'capture'}});}engine.call('scene.cinematic',{request:{command:'play'}});}catch(error){status.textContent=error.message;}});
stop.addEventListener('click',()=>{try{engine.call('scene.cinematic',{request:{command:'stop'}});status.textContent='Explore and edit this temporary copy. Save your version before closing.';}catch(error){status.textContent=error.message;}});
save.addEventListener('click',()=>{try{const snapshot=engine.call('scene.cinematic',{request:{command:'document'}});const copy={version:snapshot.version,model:snapshot.model,initial:snapshot.initial,seq:snapshot.seq,title:${JSON.stringify(i.title+' — my version')}};if(!snapshot.initial.film_branding_mode && copy.seq.length){for(const cue of reference.seq.filter(clip=>clip.op==='sound'&&clip.branding_slot)){if(!copy.seq.some(clip=>clip.op==='sound'&&clip.branding_slot===cue.branding_slot)&&(cue.branding_slot!=='outro'||copy.seq.some(clip=>clip.asset==='polynite-wordmark')))copy.seq.push(structuredClone(cue));}}copy.export={};for(const key of ['fps','resolution','encoder','quality','watermark'])if(snapshot.export?.[key]!==undefined)copy.export[key]=snapshot.export[key];const url=URL.createObjectURL(new Blob([JSON.stringify(copy)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=${JSON.stringify(i.id+'-my-version.scene')};if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=url;download.href=url;download.download=link.download;download.hidden=false;download.click();status.textContent='Your scene copy is ready. Use Download my version if the download did not start.';}catch(error){status.textContent='Stop the film before saving your version. '+error.message;}});
</script></body></html>`);}
}
console.log('Built shared tutorial catalogue, three playable scene entries and gallery.');
