// Shared by generated pages and Worker-rendered Discover/model pages.
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const APP='https://polynite.io',EXPLORE='https://explore.polynite.io';
export function renderHeader({section='',current='',app=APP,explore=EXPLORE}={}){
 const links=[[explore+'/','Explore'],[explore+'/create/','Create'],[explore+'/discover/','Discover'],[explore+'/docs/','Docs'],[explore+'/docs/mcp/','AI & MCP']];
 return `<header class="site-header"><div class="header-inner"><a class="brand" href="${app}/mcp/" aria-label="Polynite product"><img src="${app}/assets/favicon-32.png" width="24" height="24" alt=""><span class="brand-name">Polynite</span></a><nav class="primary-nav" aria-label="Main navigation">${links.map(([url,label])=>`<a href="${escape(url)}"${current===label?' aria-current="page"':''}>${escape(label)}</a>`).join('')}</nav><a class="app-link" href="${app}/">Open Polynite</a></div></header>`;
}
export function renderFooter({app=APP,explore=EXPLORE}={}){
 const groups=[['Create & explore',[[app+'/','Open Polynite'],[explore+'/create/','Procedural creation'],[explore+'/discover/','Discover creations']] ],['Learn & share',[[explore+'/docs/','Documentation'],[explore+'/docs/sharing/','Mint Link guide'],[explore+'/docs/mcp/','AI & MCP'],['https://www.youtube.com/@polynite-io','Polynite on YouTube']] ],['Get in touch',[[app+'/support/','Support'],[explore+'/about/','About Polynite'],[app+'/privacy/','Privacy'],[app+'/terms/','Terms']] ]];
 return `<footer class="site-footer"><div class="footer-inner"><div class="footer-grid"><div class="footer-brand"><a class="brand" href="${app}/mcp/"><img src="${app}/assets/favicon-32.png" width="28" height="28" alt=""><span class="brand-name">Polynite</span></a><p class="footer-slogan">Create / View / Share</p><p>Procedural worlds.<br>Experiences worth sharing.</p></div>${groups.map(([title,links])=>`<nav class="footer-group" aria-label="${escape(title)}"><p class="footer-title">${title}</p>${links.map(([url,label])=>`<a href="${url}">${label}</a>`).join('')}</nav>`).join('')}</div><div class="footer-bottom"><a class="majify-credit" href="https://majify.tech/">© 2026 Majify Technologies Inc.</a><a href="https://wake.tools/">Built with Wake ↗</a></div></div></footer>`;
}
