// Metadata only: preserve renderer scripts, loader and immutable release archives.
const fs=require('node:fs'),path=require('node:path'),{metadata,esc,ld,organization}=require('./site_metadata.cjs');const root=__dirname,p=metadata.pages.app;
const intro=`<h1>Create / View / Share procedural 3D scenes</h1><p class="sub">Build an interactive scene from procedural objects or a conversation. Explore physics, animate scene text and record an MP4 with a supported browser encoder. Share the interactive experience with a Mint Link. Imported GLB models remain part of the workflow.</p><h2>Create, interact, record</h2><ul><li>Use procedural generators and move objects in the scene.</li><li>Connect a compatible assistant to the <a href="https://explore.polynite.io/docs/mcp/">Polynite MCP server</a> for conversational creation and editing.</li><li>Experiment with physical blocks, scene text and cinematic animation.</li><li>Record and download videos; encoder availability and storage limits are documented.</li></ul><h2>Share an experience</h2><p>Use Mint Link in Share to create an interactive view. Review access settings and lifetime before sending it. <a href="https://explore.polynite.io/docs/sharing/">Mint Link guide</a>.</p><h2>Import, inspect and optimize models</h2><p>Open local GLB assets, inspect geometry and textures, and choose available optimization settings. Importing a local file is separate from cloud sharing, checkpoints and connected AI generation.</p><nav aria-label="Polynite information"><a href="/mcp/">Product</a> <a href="https://explore.polynite.io/docs/">Documentation</a> <a href="https://explore.polynite.io/docs/mcp/">Connect AI through MCP</a> <a href="https://explore.polynite.io/discover/">Public creations</a> <a href="/glb-viewer/">GLB viewer</a> <a href="/glb-optimizer/">GLB optimizer</a> <a href="/support/">Support</a> <a href="https://www.youtube.com/@polynite-io">YouTube</a></nav>`;
const targets=[root,path.join(root,'dev'),path.join(root,'web')].flatMap(base=>['index.html','app.html'].map(name=>path.join(base,name)));
const source=process.argv.indexOf('--source');if(source>=0){if(!process.argv[source+1])throw Error('Missing engine HTML source');targets.push(path.resolve(process.argv[source+1]));}
for(const file of targets){if(!fs.existsSync(file))continue;let html=fs.readFileSync(file,'utf8');html=html.replace(/<title>[^<]*<\/title>/,`<title>${esc(p.title)}</title>`);
 for(const name of ['description','og:description','twitter:description'])html=html.replace(new RegExp(`(<meta (?:name|property)="${name}" content=")[^"]*(">)`),`$1${esc(p.description)}$2`);
 for(const name of ['og:title','twitter:title'])html=html.replace(new RegExp(`(<meta (?:name|property)="${name}" content=")[^"]*(">)`),`$1${esc(p.title)}$2`);
 for(const name of ['og:image','twitter:image'])html=html.replace(new RegExp(`(<meta (?:name|property)="${name}" content=")[^"]*(">)`),`$1${metadata.image}$2`);
 html=html.replace(/(<meta property="og:image:alt" content=")[^"]*(">)/,`$1${esc(metadata.imageAlt)}$2`);
 if(file.includes(path.sep+'dev'+path.sep))html=html.replace(/<meta name="robots"[^>]*>/,'<meta name="robots" content="noindex, follow">');
 let schemaCount=0;html=html.replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/g,()=>schemaCount++===0?ld({'@context':'https://schema.org','@graph':[organization,{'@type':'WebSite',name:'Polynite',url:'https://polynite.io/',description:p.description},{'@type':'WebApplication',name:'Polynite',url:'https://polynite.io/',description:p.description,applicationCategory:'DesignApplication',operatingSystem:'Web browser',browserRequirements:'WebGPU; desktop Chromium is the exercised renderer path',publisher:{'@id':organization['@id']},featureList:['Procedural 3D scene creation','AI scene control through MCP','Interactive physics blocks','Scene text and cinematic animation','MP4 recording with a supported browser encoder','Interactive sharing through Mint Link','GLB import, inspection and optimization']}]}):'');
 html=html.replace(/(<main class="seo-content" id="intro">)[\s\S]*?(<\/main>)/,'$1'+intro+'$2');fs.writeFileSync(file,html);
}
for(const base of [root,path.join(root,'dev'),path.join(root,'web')]){const file=path.join(base,'site.webmanifest');if(fs.existsSync(file)){const manifest=JSON.parse(fs.readFileSync(file,'utf8'));manifest.description='Create procedural 3D scenes, explore physics and animation, and control Polynite through AI and MCP.';fs.writeFileSync(file,JSON.stringify(manifest,null,2)+'\n');}}
console.log('App metadata, readable fallback and manifests synchronized; renderer scripts unchanged.');
