const assert = require('node:assert/strict');
const {prepareTutorialDocument} = require('./tutorial_scene_compat.cjs');
const input = {seq:[{op:'orbit',at:0,dur:5},{op:'text',asset:'polynite-wordmark',at:5,dur:2,branding_slot:'outro',branding_tail:2},{op:'sound',at:6.14,dur:.86,branding_slot:'outro'}]};
const supported = prepareTutorialDocument(input,true);
assert.deepEqual(supported,input); assert.notEqual(supported,input);
const legacy = prepareTutorialDocument(input,false);
assert.equal(legacy.seq.length,5);
assert.equal(legacy.seq[1].at,5); assert.equal(legacy.seq[1].branding_slot,undefined);
assert.equal(legacy.seq[2].branding_slot,'outro');
assert.deepEqual(legacy.seq[3],{op:'set',at:5,dur:.7,film_fade:1});
assert.deepEqual(legacy.seq[4],{op:'hold',at:5,dur:2});
assert.equal(input.seq.length,3); assert.equal(input.seq[1].branding_tail,2);
assert.deepEqual(prepareTutorialDocument(legacy,false),legacy);
assert.deepEqual(prepareTutorialDocument({seq:[{op:'hold',dur:5}]},false),{seq:[{op:'hold',dur:5}]});
console.log('PASS: old engine closing fallback, sound anchoring, immutable reference and repeated preparation');
