const fs=require('node:fs'),path=require('node:path');
const {esc}=require('./site_metadata.cjs');
const {prepareTutorialDocument,restoreTutorialCues,preserveTutorialControls}=require('./tutorial_scene_compat.cjs');
module.exports=function tutorialViewPage(i){
 const version=fs.readFileSync(path.join(__dirname,'version.txt'),'utf8').trim();if(!/^v\d{4,6}$/.test(version))throw Error('Invalid engine release');
 const script=fs.readFileSync(path.join(__dirname,'public-site-src/tutorial-view.js'),'utf8');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(i.title)} — Polynite Tutorial</title><meta name="description" content="${esc(i.description)} Open the scene and make it your own."><link rel="canonical" href="${i.open}"><meta property="og:title" content="${esc(i.title)} — Polynite"><meta property="og:description" content="${esc(i.description)}"><meta property="og:url" content="${i.open}"><meta property="og:image" content="${i.poster}"><style>
 html,body{height:100%;margin:0;background:#0b0d12;color:#e8eef7;font:14px system-ui}body{display:flex;flex-direction:column;height:100dvh}header{flex-shrink:0;display:flex;gap:8px;align-items:center;padding:8px 12px;border-bottom:1px solid #26313d}a{color:#4fd1e0}strong{flex:1;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}button,summary{font:inherit;cursor:pointer}button{padding:7px 12px;background:#4fd1e0;border:0;border-radius:7px;color:#071218}button:disabled{opacity:.45;cursor:wait}#pause{background:transparent;color:#c9d5e4;border:1px solid #354557}details{position:relative}summary{padding:7px 10px;list-style:none;font-size:18px}summary::-webkit-details-marker{display:none}.menu{position:absolute;right:0;top:100%;z-index:2;min-width:190px;padding:12px;background:#101720;border:1px solid #354557;border-radius:8px;box-shadow:0 8px 24px #0008}.menu{max-height:65vh;overflow:auto}.menu .guide summary{font-size:13px;padding:8px 0}.guide ol{padding-left:20px;max-width:280px;font-size:12px;line-height:1.5}.guide li+li{margin-top:8px}.menu p{margin:8px 0;color:#91a4b8;font-size:12px}.menu a{display:block;padding:6px 0}iframe{width:100%;flex:1;min-height:0;border:0}#status{position:fixed;bottom:12px;left:50%;transform:translateX(-50%);z-index:3;background:#101720ee;border:1px solid #354557;border-radius:8px;padding:8px 12px;max-width:80vw;font-size:12px;pointer-events:none}#status:empty{display:none}@media(max-width:600px){header{flex-wrap:wrap;padding:6px 8px;gap:6px}strong{flex-basis:calc(100% - 110px)}button{padding:7px 10px}header>a{font-size:12px}#replay{margin-left:auto}.menu{min-width:170px}}
 </style></head><body data-scene="${esc(new URL(i.scene).pathname)}" data-title="${esc(i.title)}" data-id="${esc(i.id)}" data-ending-preview="${i.preset==='polynite-ending-v4'}"><header><a href="https://explore.polynite.io/docs/#examples" aria-label="Back to tutorials">← Tutorials</a><strong>${esc(i.title)}</strong><button id="replay" disabled>Play</button><button id="pause" disabled>Pause</button><button id="save" disabled>Save scene</button><details><summary aria-label="Scene options">⋯</summary><div class="menu"><button id="reset" disabled>Reset scene</button><button id="settings" disabled hidden>Scene settings</button><a href="${i.scene}" download>Download original scene</a>${i.steps?`<details class="guide"><summary>Tutorial steps</summary><ol>${i.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol></details>`:''}<p>This is your own temporary copy. Save it to keep your changes.</p></div></details></header><p id="status" role="status">Loading scene…</p><iframe src="/tutorial-view/?tutorial_view=1&amp;_v=${version}" title="Polynite interactive tutorial"></iframe><script>
 ${prepareTutorialDocument.toString()}
 ${restoreTutorialCues.toString()}
 ${preserveTutorialControls.toString()}
 ${script}
 </script></body></html>`;
};
