const frame=document.querySelector('iframe'),status=document.querySelector('#status'),replay=document.querySelector('#replay'),pause=document.querySelector('#pause'),reset=document.querySelector('#reset'),save=document.querySelector('#save');
const includeOutro=document.body.dataset.endingPreview==='true';
let engine,reference,transportTimer,noticeTimer,downloadUrl;
const call=(method,command,extra={})=>engine.call(method,{request:{command,...extra}});
function notice(text,sticky=false){clearTimeout(noticeTimer);status.textContent=text;if(text&&!sticky)noticeTimer=setTimeout(()=>status.textContent='',3500);}
function watchTransport(){clearInterval(transportTimer);transportTimer=setInterval(()=>{try{const film=call('scene.cinematic','status');if(!film.playing){clearInterval(transportTimer);pause.textContent='Pause';pause.disabled=!call('scene.physics','status').body_count;replay.disabled=false;save.disabled=false;console.info('[tutorial-effects]',JSON.stringify({impacts:call('scene.physics','status').impact_sounds,live:engine.call('scene.describe').sound?.live}));const endSteps=call('scene.physics','status').steps;setTimeout(()=>{try{const current=call('scene.cinematic','status');if(!current.playing&&current.time===film.time)console.info('[tutorial-continuity]',JSON.stringify({steps_at_end:endSteps,steps_after:call('scene.physics','status').steps}));}catch{}},1000);console.info('[tutorial-playback]',JSON.stringify({continuous:engine.call('scene.capabilities').commands?.cinematic_continue_scene===true,end_behavior:film.end_behavior}));notice(engine.call('scene.capabilities').commands?.cinematic_continue_scene?'Film finished · keep exploring':'Film finished');}}catch(error){clearInterval(transportTimer);notice(error.message,true);}},250);}
const until=Date.now()+90000;
const timer=setInterval(async()=>{try{engine=frame.contentWindow.polynite;if(!engine?.call){if(Date.now()>until){clearInterval(timer);notice('Viewer unavailable. Download the original from Scene options.',true);}return;}if(call('scene.cinematic','status').export.active)throw Error('Viewer is busy');clearInterval(timer);const response=await fetch(document.body.dataset.scene);if(!response.ok)throw Error('Scene download failed');reference=await response.json();const copy=prepareTutorialDocument(reference,call('scene.cinematic','status').branding?.outro_tail_supported,!includeOutro,call('scene.cinematic','status').branding?.text_spatial_exit_supported===true,call('scene.cinematic','status').branding?.text_exit_sync_supported===true&&call('scene.cinematic','status').branding?.camera_smooth_transitions_supported===true&&call('scene.cinematic','status').branding?.text_curvature_supported===true&&call('scene.cinematic','status').branding?.text_camera_facing_supported===true);if(!engine.call('scene.describe').sound?.live&&!engine.call('scene.capabilities').cinematic?.branding)copy.seq=copy.seq.filter(c=>c.op!=='sound');call('scene.cinematic','load_document',{document:copy,start_paused:true});replay.disabled=false;pause.disabled=true;reset.disabled=false;save.disabled=false;startTutorial(false);notice(reference.seq.some(c=>c.exit==='spatial_type')&&!call('scene.cinematic','status').branding?.text_spatial_exit_supported?'Some text effects need a viewer update.':'');}catch(error){clearInterval(timer);notice('Could not open scene: '+error.message,true);}},250);
async function startTutorial(gesture){replay.disabled=true;try{notice('Starting…');const viewer=frame.contentWindow;if(gesture){const awakened=viewer.vmeshAudioGesture?await viewer.vmeshAudioGesture():false;console.info('[tutorial-audio]',JSON.stringify({awakened,live:engine.call('scene.describe').sound?.live}));const deadline=Date.now()+2000;while(!engine.call('scene.describe').sound?.live&&Date.now()<deadline)await new Promise(r=>setTimeout(r,50));}call('scene.cinematic','stop');if(engine.call('scene.describe').sound?.live){const current=call('scene.cinematic','document');call('scene.cinematic','replace',{seq:restoreTutorialCues(current.seq,reference,includeOutro)});}if(call('scene.physics','status').body_count){call('scene.physics','resume');call('scene.cinematic','capture');}call('scene.cinematic','play');save.disabled=true;pause.disabled=false;replay.textContent='Replay';pause.textContent='Pause';notice('');watchTransport();}catch(error){save.disabled=false;notice(error.message,true);}finally{replay.disabled=false;}}
replay.addEventListener('click',()=>startTutorial(true));
pause.addEventListener('click',()=>{try{const film=call('scene.cinematic','status');if(film.playing){call('scene.cinematic',film.paused?'resume':'pause');pause.textContent=film.paused?'Pause':'Continue';}else{const physics=call('scene.physics','status');call('scene.physics',physics.paused?'resume':'pause');pause.textContent=physics.paused?'Pause':'Continue';}}catch(error){notice(error.message,true);}});
save.addEventListener('click',()=>{try{if(call('scene.cinematic','status').playing){notice('Wait for the film to finish before saving.',true);return;}const snapshot=call('scene.cinematic','document');const copy={version:snapshot.version,model:snapshot.model,initial:snapshot.initial,seq:restoreTutorialCues(snapshot.seq,reference,true),title:document.body.dataset.title+' — my scene'};copy.export={};for(const key of ['fps','resolution','encoder','quality','watermark'])if(snapshot.export?.[key]!==undefined)copy.export[key]=snapshot.export[key];const url=URL.createObjectURL(new Blob([JSON.stringify(copy)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=document.body.dataset.id+'-my-scene.scene';link.textContent='Save scene';link.style.display='none';document.body.append(link);link.click();link.remove();if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=url;notice('Scene saved');}catch(error){notice(error.message,true);}});
window.addEventListener('pagehide',()=>{clearInterval(timer);clearInterval(transportTimer);clearTimeout(noticeTimer);if(downloadUrl)URL.revokeObjectURL(downloadUrl);});

reset.addEventListener('click',()=>{try{clearInterval(transportTimer);call('scene.cinematic','stop');if(call('scene.physics','status').body_count)call('scene.physics','pause');replay.textContent='Play';pause.textContent='Pause';pause.disabled=true;save.disabled=false;reset.closest('details').open=false;notice('Scene reset');}catch(error){notice(error.message,true);}});
